baseURL = "https://williamzujkowski.github.io/"  # Change this to your live URL (or subpath if needed)
languageCode = "en-us"
title = "William Zujkowski's Personal Website"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
lastmod = true

[params]
  author = "William Zujkowski"
  description = "Forget cybersecurity audits—my son red teams my sanity daily, finding new techniques to evade his vegetables and new exploits in our bedtime routine."
  github = "williamzujkowski"
  linkedin = "williamzujkowski"
  url = "https://williamzujkowski.github.io"
  keywords = "blog, personal, Hugo, github-style"
  rss = true
  lastmod = true
  favicon = "/images/header-icon.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/header-icon.png"
  location = "USA"
  userStatusEmoji = "😀"
  enableGitalk = false
  enableSearch = false
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

[[params.links]]
  title = "Website"
  href = "https://williamzujkowski.github.io"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = ""


[caches]
  [caches.images]
    dir = ':cacheDir/images'