#!/usr/bin/env python3
"""Build a bounded issue excerpt while retaining the complete report artifact."""
import argparse
from datetime import UTC, datetime
from pathlib import Path

MAX_BODY_BYTES = 50_000


def build_issue_body(report: str, run_url: str, date: str) -> str:
    """Bound the entire UTF-8 body, including links and a visible truncation notice."""
    prefix = f'**Date:** {date}\n\n'
    footer = ('\n\n[Full report and validation artifacts](' + run_url + ') '
              '(download `citation-validation-report`).\n\n'
              '*Generated by the citation validation workflow.*')
    body = prefix + report + footer
    if len(body.encode('utf-8')) <= MAX_BODY_BYTES:
        return body
    notice = '\n\n**Report excerpt truncated.** The full report is retained in the linked run artifacts.'
    budget = MAX_BODY_BYTES - len((prefix + notice + footer).encode('utf-8'))
    if budget <= 0:
        raise ValueError('Issue metadata exceeds the body budget')
    # Byte slicing never splits a UTF-8 character in the returned text. Prefer a
    # whole report line, retaining the headline and broken-link section first.
    excerpt = report.encode('utf-8')[:budget].decode('utf-8', errors='ignore')
    if '\n' in excerpt:
        excerpt = excerpt.rsplit('\n', 1)[0]
    return prefix + excerpt + notice + footer


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', type=Path, required=True)
    parser.add_argument('--run-url', required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    body = build_issue_body(args.report.read_text(encoding='utf-8'), args.run_url,
                            datetime.now(UTC).date().isoformat())
    args.output.write_text(body, encoding='utf-8')


if __name__ == '__main__':
    main()
